### ISSUE TITLE
Запрос ReadProcessMemory или WriteProcessMemory был выполнен только частично

### ISSUE THREAD

**Issue by Kawoshin1995** [BlendLog/MinerSearch#13]
Вот что вылезает при запуске, NET Framework 4.7.1 есть
![Снимок экрана 2024-10-17 011310](https://github.com/user-attachments/assets/9b83543b-cd4d-4986-90cd-f1b031110f99)

**Comment by Kawoshin1995** [comment]
Хотел бы добавить что сначала какие то процессы сканирует а потом это вылезает

**Comment by BlendLog** [comment]
Приветствую, проблема известная и будет исправлена в следующем обновлении. В качестве временного обходного решение запустить приложение с отключенной проверкой на руткит.

1. Запустить командную строку от админа
2. С зажатым shift + правый клик по приложению MinerSearch - выбрать "копировать как путь"
3. Вставить путь в командную строку и через пробел дописать --no-rootkit-check 

Если не помогло - добавить приложение в исключение антивируса

**Comment by Kawoshin1995** [comment]
Помогло, спасибо большое!
