### ISSUE TITLE
Программа не запускается на ноутбуке

### ISSUE THREAD

**Issue by DmSergienko** [BlendLog/MinerSearch#3]
Программа версии 1.4.7.2 не запускается на ноутбуке Lenovo. Выводится вот такое сообщение об ошибке (см. прилагаемое видео

https://github.com/user-attachments/assets/2776c107-694a-49b2-b863-ebf583efc388

)

**Comment by BlendLog** [comment]
разрешения экрана какое стоит?

**Comment by BlendLog** [comment]
как временное решение задать размер равный 1024 x 768, или в настройках командной строки задать меньше размер шрифта.
![изображение](https://github.com/user-attachments/assets/4a0829c5-d689-4f57-9d7b-eb8ee6d06d36)
![изображение](https://github.com/user-attachments/assets/40aa384b-b5bb-44b6-ac0d-4e46dcc9862e)

**Comment by DmSergienko** [comment]
Спасибо за совет! Вечером изменю параметры, напишу результаты

**Comment by DmSergienko** [comment]
Разрешение экрана было 1920 на 1080.
Помогло уменьшение размеар шрифта до 10 кегля.
Программа отработала, нашла и удалила зловредные файлы, все отлично!
Благодарю за оперативный ответ!
![2024-07-16_210842](https://github.com/user-attachments/assets/8a5bcec1-2a4e-48ee-a712-05b250ad1524)

**Comment by BlendLog** [comment]
Ого, супер! Будет плюсом, если пришлете архивом логи из каталога C:\_MinerSearchLogs. Это для статистики.

**Comment by DmSergienko** [comment]
Хорошо, вечером вытащу логи. Куда их сбросить?

**Comment by BlendLog** [comment]
на почту BlendLog@bk.ru или в телеграм @BlendLog
