### ISSUE TITLE
Проблема после проверки TermService

### ISSUE THREAD

**Issue by 33ip** [BlendLog/MinerSearch#5]
**Вылезает окно с необработанным исключением (Ссылка на объект не указывает на экземпляр объекта)**

![MinerSearch_v1 4 7 3_5ysV8PK1a6](https://github.com/user-attachments/assets/bf1faf97-be34-4d9e-87ae-a22c410b576a)

- Из архива распаковал все, попробовал сначала извлечь все в диск C, думал проблема в этом, но так и не понял, перезапускал раза 3-4 и от имени администратора тоже

![explorer_SJT5PM0fJ3](https://github.com/user-attachments/assets/7e7654c8-758b-44b8-88bc-f9b005ae6249)

- Попробовал ещё из другого файла извлечь все в папку с MinerSearh, то-бишь Source Code, т.к. подумал что-то отсутствует для корректной работы программы, ещё и из-за описания, тоже не помогло

![explorer_cTG28O5b0G](https://github.com/user-attachments/assets/1945992c-ed11-4e24-a778-5a13ecabbeea)

- _Так и не понял, в чем же дело_

> Винда обычная 10-тка, но урезанная с помощью программ

**Comment by BlendLog** [comment]
> _Винда обычная 10-тка, но урезанная с помощью программ_

В этом и проблема. Обходное решение это либо восстанавливать то, что было вырезано твикером, либо пропустить сканирование служб, запустив приложение из командной строки:

_MinerSearch.exe --no-services_

**Comment by 33ip** [comment]
> > _Винда обычная 10-тка, но урезанная с помощью программ_
> 
> В этом и проблема. Обходное решение это либо восстанавливать то, что было вырезано твикером, либо пропустить сканирование служб, запустив приложение из командной строки:
> 
> _MinerSearch.exe --no-services_

Жаль что так, надеюсь в будущем найдёте для урезанных виндовс решения

**Comment by BlendLog** [comment]
Приветствую. Решение было найдено и добавлено в новую версию (1.4.7.4)
