### ISSUE TITLE
Проблема с панелью задач.

### ISSUE THREAD

**Issue by OldFikus** [BlendLog/MinerSearch#6]
Доброго времени суток! Ваша программа действительно хороша, благодаря ей у меня ПК начал работать как швейцарские часы, однако... После чистки ПК у меня по какой-то причине долго запускается панель задач (Примерно 3-5 минут). Перед чисткой пк у меня как раз таки проблема была с проводником, запускался Explorer.EXE, из-за чего я и скачал данную утилиту. 
Когда я через диспетчер задач отключал Explorer.EXE, у меня пропадала и панель задач, и рабочий стол. 
То есть смею предположить что майнер был вшит в Проводник, а утилита в свою очередь удалила что-то связанное с проводником, из-за чего он стал долго загружаться, а также в Параметрах у меня не работает вкладка Центр обновления виндовс. 

Обращаюсь с надеждой на фидбек, возможно уже обращались с подобной проблемой. Опробовал все способы восстановления которые только предлагали (кроме переустановки винды), ничего не помогало.
За ранее спасибо

**Comment by BlendLog** [comment]
Приветствую! Приложение не удаляет компоненты проводника, а лишь прерывает его вредоносный клон-процесс, который ссылается на настоящий Explorer.exe. Удаляется "инициатор внедрения" вируса. Твикерами никакими не пользовались? Предполагаю что причину стоит искать в этом направлении.

**Comment by BlendLog** [comment]
А что с Центром обновлений? Что пишет

**Comment by OldFikus** [comment]
Твинкерами не пользовался. Когда-то очень давно пользовался, но с тех пор стоит чистая винда и данную затею я оставил в прошлом, ибо за "улучшениями" следовали неприятные последствия. 
Центр обновлений... Пустая страница, 
![image](https://github.com/user-attachments/assets/a9c1fdfe-2c4a-4a0d-8fba-7260e8f31b21)

**Comment by OldFikus** [comment]
Я бы мог предоставить лог проверки ПК, если укажете где именно его найти (ибо самому было интересно, нашел только то что удалила утилита)
Возможно там что-то есть, ибо во время проверки видел в пробегающих строчках изменение реестра.

**Comment by BlendLog** [comment]
По умолчанию логи лежат на C:\_MinerSearchLogs\

**Comment by OldFikus** [comment]
[MinerSearch_23_50_2024-12_12.log](https://github.com/user-attachments/files/16787731/MinerSearch_23_50_2024-12_12.log)

**Comment by BlendLog** [comment]
Так, майнер удалён. Запустите командную строку от админа, введите
sc query wuauserv

затем скрин

**Comment by OldFikus** [comment]
![image](https://github.com/user-attachments/assets/7720c79a-06e7-4c4d-8115-4f2437ab4e23)

**Comment by BlendLog** [comment]
sc start wuauserv

**Comment by OldFikus** [comment]
![image](https://github.com/user-attachments/assets/63029c60-6603-40fc-8d46-f360e24a0ca1)

**Comment by BlendLog** [comment]
Появилась страница?

**Comment by OldFikus** [comment]
Нет, всё также пуста

**Comment by OldFikus** [comment]
Перезапустил пк, всё также и осталось.

**Comment by BlendLog** [comment]
Поступим подругому. Win + q, набрать Службы, пролистать в самый низ где Центр Обновлений Windows, правый клик - запустить. Что пишет?

**Comment by BlendLog** [comment]
Даже так. Похоже майнер удалил службу обновлений. Из вариантов решения
1) В командной строке от админа написать `sfc /scannow` и подождать.
2) Также в командной строке `dism /Online /Cleanup-Image /RestoreHealth` и подождать
3) Пробовать этот способ восстановления https://remontka.pro/windows-update-service-missing/

**Comment by BlendLog** [comment]
Ещё вопрос, после загрузки рабочий стол появляется сразу или черный экран? Или не сразу появляются значки на панеле задач?

**Comment by OldFikus** [comment]
> Даже так. Похоже майнер удалил службу обновлений. Из вариантов решения
> 
> 1. В командной строке от админа написать `sfc /scannow` и подождать.
> 2. Также в командной строке `dism /Online /Cleanup-Image /RestoreHealth` и подождать
> 3. Пробовать этот способ восстановления https://remontka.pro/windows-update-service-missing/

1 и 2 способы уже проверил, поэтому перейду сразу к третьему.

**Comment by OldFikus** [comment]
> Ещё вопрос, после загрузки рабочий стол появляется сразу или черный экран? Или не сразу появляются значки на панеле задач?

Рабочий стол сразу появляется, а вот панель задач висит без значков, Вернее сказать на ней не появляются установленные мной значки, а также язык и иконка звука. 
+ приложения из автозагрузки не запускаются пока не прогрузится панель управления. Я могу пользоваться Поиском (лупой), могу пользоваться Win, но самой панели будто что-то мешает запуститься.

**Comment by OldFikus** [comment]
> > Ещё вопрос, после загрузки рабочий стол появляется сразу или черный экран? Или не сразу появляются значки на панеле задач?
> 
> Рабочий стол сразу появляется, а вот панель задач висит без значков, Вернее сказать на ней не появляются установленные мной значки, а также язык и иконка звука.
> приложения из автозагрузки не запускаются пока не прогрузится панель управления. Я могу пользоваться Поиском (лупой), могу пользоваться Win, но самой панели будто что-то мешает запуститься.

**Comment by OldFikus** [comment]
> Ещё вопрос, после загрузки рабочий стол появляется сразу или черный экран? Или не сразу появляются значки на панеле задач?

Рабочий стол сразу появляется, а вот панель задач висит без значков, Вернее сказать на ней не появляются установленные мной значки, а также язык и иконка звука.
приложения из автозагрузки не запускаются пока не прогрузится панель управления. Я могу пользоваться Поиском (лупой), могу пользоваться Win, но самой панели будто что-то мешает запуститься.

**Comment by OldFikus** [comment]
> Ещё вопрос, после загрузки рабочий стол появляется сразу или черный экран? Или не сразу появляются значки на панеле задач?

Рабочий стол сразу появляется, а вот панель задач висит без значков, Вернее сказать на ней не появляются установленные мной значки, а также язык и иконка звука. Приложения из автозагрузки не запускаются пока не прогрузится панель управления. Я могу пользоваться Поиском (лупой), могу пользоваться Win, но самой панели будто что-то мешает запуститься.

**Comment by OldFikus** [comment]
Прошу прощения. Не заметил что цитирую вместо редактирования.

**Comment by BlendLog** [comment]
> Вернее сказать на ней не появляются установленные мной значки, а также язык и иконка звука.

Можно попробовать в этот момент нажать Win + R, затем ввести `sihost.exe` рабочий стол должен моргнуть и значки появится.

**Comment by OldFikus** [comment]
> Можно попробовать в этот момент нажать Win + R, затем ввести sihost.exe рабочий стол должен моргнуть и значки появится.

Да, это сработало. Давно не удивлялся подобному, сколько пользуюсь пк

**Comment by OldFikus** [comment]
Ещё одна заметка.
- При включении пк, около 30 секунд входит в учётную запись. 
Сама ОС установлена на SSD, и проблема также возникла неожиданно (тут я точно не уверен после проверки или до. Опять же, не виню вас и ваше ПО. Без него я так бы и сидел с майнерами, которых даже Dr Web не видел)

**Comment by OldFikus** [comment]
> > Даже так. Похоже майнер удалил службу обновлений. Из вариантов решения
> > 
> > 1. В командной строке от админа написать `sfc /scannow` и подождать.
> > 2. Также в командной строке `dism /Online /Cleanup-Image /RestoreHealth` и подождать
> > 3. Пробовать этот способ восстановления https://remontka.pro/windows-update-service-missing/
> 
> 1 и 2 способы уже проверил, поэтому перейду сразу к третьему.

Проверил 3й способ, проблема осталась та же.

**Comment by OldFikus** [comment]
Такое чувство, будто придётся переустанавливать систему. К чему конечно не хотелось бы приходить...

**Comment by BlendLog** [comment]
Есть ещё пару зацепок. В cmd от админа запустить
sc query UsoSvc_bkp

Есть реакция?

**Comment by OldFikus** [comment]
> Есть ещё пару зацепок. В cmd от админа запустить sc query UsoSvc_bkp
> 
> Есть реакция?

С центром обновления особо нет, только это прогрузилось спустя некоторое время. 
![image](https://github.com/user-attachments/assets/fc26aa2c-acd5-47e8-8809-3636aab37068)

В командной строке таков результат 
![image](https://github.com/user-attachments/assets/2ea8b618-80ec-443d-a3ea-1ee97ff19948)

**Comment by BlendLog** [comment]
Опа. А давайте так, нажмите Win + R. введите regedit, перейдите в ветку `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services` и найдите там UsoSvc_bkp, рядом есть UsoSvc без приставки Bkp?

**Comment by OldFikus** [comment]
> Опа. А давайте так, нажмите Win + R. введите regedit, перейдите в ветку `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services` и найдите там UsoSvc_bkp, рядом есть UsoSvc без приставки Bkp?

Есть

**Comment by BlendLog** [comment]
`UsoSvc` переименуйте в `UsoSvc_`, а тот что `UsoSvc_bkp` переименовать обратно в `UsoSvc`. Затем в командной строке от админа `sc start UsoSvc`. Проверить страницу с обновлениями.

**Comment by OldFikus** [comment]
О МОЙ БОГ, ОНО РАБОТАЕТ

**Comment by OldFikus** [comment]
Вы гениальны, сэр. Склоняю голову перед вами

**Comment by BlendLog** [comment]
Супер! Рад был помочь

**Comment by OldFikus** [comment]
Осталось как-то решить вопрос с панелью задач. В остальном премного благодарен.
Попробую теперь поискать информацию насчёт автоматизации запуска этой утилиты.

> Можно попробовать в этот момент нажать Win + R, затем ввести `sihost.exe` рабочий стол должен моргнуть и значки появится.

**Comment by OldFikus** [comment]
Возможно он также встроен в автозагрузку, ибо у меня всегда при запуске системы происходила такая же реакция как при ручном запуске,

**Comment by OldFikus** [comment]
Точно, Вы вновь оказались правы, сэр.
Я уж было собрался добавлять sihost.exe в автозагрузку. (Самое банальное что пришло в голову)
Система вновь запустилась быстро и панель задач также моментально загрузилась. Спасибо вам огромное, чтобы я без вас делал. 
По правде говоря я собирался переустанавливать винду, ибо при откате системы могли вернуться и удалённые майнеры, поэтому решил попытать удачу и обратиться к вам. 
Даже не знаю как вас отблагодарить кроме как поддержать финансово...

**Comment by OldFikus** [comment]
Пожалуй можно закрывать данный тред, однако если посчитаете целесообразным, можете оставить его видимым для тех, кто возможно столкнётся в будущем с подобной проблемой.

**Comment by BlendLog** [comment]
> Даже не знаю как вас отблагодарить кроме как поддержать финансово...
Буду благодарен за поддержку

Для желающих сказать "спасибо":
Boosty:  https://boosty.to/blendlog/donate
Юмани: 4100 1161 1264 0968
Ton: UQCrg_SSZJy71gvm6CQWnQJUoQbMErUdMbBdBvNrZimeNTmU

Либо Cбер по номеру, тут оставлять не хочу, напишите в лс в телеграм @BlendLog
