### ISSUE TITLE
Ошибочное создание

### ISSUE THREAD

**Issue by yurals** [BlendLog/MinerSearch#8]

**Comment by BlendLog** [comment]
Приветствую. Так что с зависанием?

**Comment by yurals** [comment]
Здравствуйте!
Спасибо за Ваше письмо, оно не останется без внимания.

---
С уважением,
Юрий
тел. +7 (950) 004-06-56

**Comment by yurals** [comment]
Здравствуйте!Было зависание на проверке одного файла, очень долго программка висела и ничего не происходило, закрывал ее несколько раз.После очередного запуска файл проверку прошел и весь дальнейший процесс успешно отработал.К сожалению, мне это не помогло. Видимо, дело не в вирус-майнинге.08:54, 4 сентября 2024 г., BlendLog ***@***.***>:
Приветствую. Так что с зависанием?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
